/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:gui:364064:
  appc.background(230);
} //_CODE_:gui:364064:

public void button1_click1(GButton source, GEvent event) { //_CODE_:screenshot_button:805889:
  println("screenshot_button - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:screenshot_button:805889:

public void button1_click2(GButton source, GEvent event) { //_CODE_:grid_button:697262:
  if (draw_g){draw_g = false;}
  else{draw_g = true;}
  
  println("grid_button - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:grid_button:697262:

boolean isFurnitureSelected = false;  
Furniture selectedFurniture = null;  // To store the selected furniture

void dropList1_click1(GDropList source, GEvent event) {
  println("FurnitureList - GDropList >> GEvent." + event + " @ " + millis());

  String selectedItem = source.getSelectedText();

  if (selectedItem == null) return;

  if (selectedItem.equals("Bed")) {
    selectedFurniture = new Furniture(0, 0, 125f, 80f, 0, color(255, 0, 100), true);
  } else if (selectedItem.equals("Couch")) {
    selectedFurniture = new Furniture(0, 0, 150f, 75f, 0, color(100, 0, 255), true);
  } else if (selectedItem.equals("Table")) {
    selectedFurniture = new Furniture(0, 0, 100f, 100f, 0, color(0, 255, 50), true);
  } else if (selectedItem.equals("Chair")) {
    selectedFurniture = new Furniture(0, 0, 50f, 50f, 0, color(200, 100, 50), true);
  } else if (selectedItem.equals("Carpet")) {
    selectedFurniture = new Furniture(0, 0, 200f, 100f, 0, color(255, 200, 0), true);
  } else {
    return; // Unknown item
  }

  isFurnitureSelected = true;  
} //_CODE_:FurnitureList:873779:

public void button1_click3(GButton source, GEvent event) { //_CODE_:delete_button:486369:
  println("delete_button - GButton >> GEvent." + event + " @ " + millis());
  if(delete_bool == false){delete_bool = true;print(true);}
  else if (delete_bool){delete_bool = false;}
  
} //_CODE_:delete_button:486369:
public void Rotation(GCustomSlider source, GEvent event) { //_CODE_:Rotate_Slider:610432:
  println("Rotate_Slider - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:Rotate_Slider:610432:

public void RoomX(GCustomSlider source, GEvent event) { //_CODE_:Room_X:797839:
  roomX = source.getValueF();
  room.resize(roomX, roomY);
  furnitureList.clear();
  room.clearFurniture();
}

public void RoomY(GCustomSlider source, GEvent event) { //_CODE_:Room_Y:251960:
  roomY = source.getValueF();
  room.resize(roomX, roomY);
  furnitureList.clear();
  room.clearFurniture();
}


// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  gui = GWindow.getWindow(this, "Window title", 0, 0, 500, 400, JAVA2D);
  gui.noLoop();
  gui.setActionOnClose(G4P.KEEP_OPEN);
  gui.addDrawHandler(this, "win_draw1");
  screenshot_button = new GButton(gui, 52, 14, 80, 30);
  screenshot_button.setText("Screenshot");
  screenshot_button.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  screenshot_button.addEventHandler(this, "screenshot_Button");
  grid_button = new GButton(gui, 275, 16, 108, 30);
  grid_button.setText("Toggle Grid");
  grid_button.addEventHandler(this, "button1_click2");
  FurnitureList = new GDropList(gui, 160, 27, 90, 120, 5, 10);
  FurnitureList.setItems(loadStrings("list_873779"), 0);
  FurnitureList.addEventHandler(this, "dropList1_click1");
  delete_button = new GButton(gui, 52, 61, 80, 30);
  delete_button.setText("Delete");
  delete_button.setLocalColorScheme(GCScheme.RED_SCHEME);
  delete_button.addEventHandler(this, "button1_click3");
  Rotate_Slider = new GCustomSlider(gui, 239, 194, 154, 56, "grey_blue");
  Rotate_Slider.setShowValue(true);
  Rotate_Slider.setLimits(1, 0, 270);
  Rotate_Slider.setNbrTicks(4);
  Rotate_Slider.setStickToTicks(true);
  Rotate_Slider.setNumberFormat(G4P.INTEGER, 0);
  Rotate_Slider.setOpaque(true);
  Rotate_Slider.addEventHandler(this, "Rotation");
  label1 = new GLabel(gui, 277, 174, 80, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Rotation");
  label1.setOpaque(false);
  Room_X = new GCustomSlider(gui, 48, 186, 136, 44, "grey_blue");
  Room_X.setShowValue(true);
  Room_X.setLimits(600, 0, 800);
  Room_X.setNbrTicks(17);
  Room_X.setStickToTicks(true);
  Room_X.setNumberFormat(G4P.INTEGER, 0);
  Room_X.setOpaque(false);
  Room_X.addEventHandler(this, "RoomX");
  Room_Y = new GCustomSlider(gui, 49, 256, 134, 45, "grey_blue");
  Room_Y.setShowValue(true);
  Room_Y.setLimits(600, 0, 800);
  Room_Y.setNbrTicks(17);
  Room_Y.setStickToTicks(true);
  Room_Y.setNumberFormat(G4P.INTEGER, 0);
  Room_Y.setOpaque(false);
  Room_Y.addEventHandler(this, "RoomY");
  label2 = new GLabel(gui, 72, 166, 80, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Room X");
  label2.setOpaque(false);
  label3 = new GLabel(gui, 71, 235, 80, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Room Y");
  label3.setOpaque(false);
  gui.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow gui;
GButton screenshot_button; 
GButton grid_button; 
GDropList FurnitureList; 
GButton delete_button; 
GCustomSlider Rotate_Slider; 
GLabel label1; 
GCustomSlider Room_X; 
GCustomSlider Room_Y; 
GLabel label2; 
GLabel label3; 
